language: node_js

node_js:
  - "node"  # latest stable release
  - "lts/*" # latest LTS release

script:
  - npm run lint
  - npm run test:cover

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
    code_climate:
        repo_token: d46a480972b9542986bef5f14563522aa4ad65a9122fa68158de52d54d044933
